### ISSUE TITLE
Error:  URI must be ascii only

### ISSUE THREAD

**Issue by roTokyo** [keithmifsud/jekyll-target-blank#33]
Thanks you for your plug-in!
I would like to use it but some of the URL I use have **Kanji**'s.
Do you think you'll upgrade in a future?

**Comment by keithmifsud** [comment]
Hi @roTokyo you're welcome :smile: What is "Kanji" please?

**Comment by roTokyo** [comment]
Sorry, kanji is the way japanese (chinese) are writing.
For example: 私に名前はロベルトです。(My name is Roberto)
With an URL like: http://anyway-grapes.jp/blog/世田谷梅まつりと世田谷名物梅大福%E3%80%80/
your plug-in generate an error 😂.


Il giorno 07/mar/2019, alle ore 19:55, Keith Mifsud <notifications@github.com> ha scritto:

**Comment by keithmifsud** [comment]
Thanks for the explanation  in :cn: I'd love to help but I wouldn't even know where to start. If anyone want to take this up I will help with testing etc.

**Comment by roTokyo** [comment]
I hope someone will!
Unfortunately I’m less than a newbie, just an amateur with a few knowledge of htlm and css and no programming skills at all!
I cann’t be helpfull.

Sorry, my bad asking!
Have a nice day
Ro

Il giorno 08/mar/2019, alle ore 11:58, Keith Mifsud <notifications@github.com> ha scritto:

**Comment by keithmifsud** [comment]
Hi again,

I think this should still work as it is though. If you have time, please give an example of the URLs you tried, some that worked and some that did not. If your repo is public, please share it too. I'll take another look at it asap.

**Comment by roTokyo** [comment]
Hi, sorry I’m late!
I did another test today, but with the plugin jekyll will not compile my site with the error:

> jekyll 3.8.5 | Error:  URI must be ascii only ...

My repository is here: https://github.com/roTokyo/Journey

Thanks!

Il giorno 08/mar/2019, alle ore 15:26, Keith Mifsud <notifications@github.com> ha scritto:

**Comment by keithmifsud** [comment]
Hi.. no worries :smile: 

Does the site compile without this plugin? URI is used by Jekyll itself too. It's a Ruby library. This plugin also uses it. Please let me know if the site builds fine with this plugin disabled. If it is, then I can try a few things.

Thanks

**Comment by roTokyo** [comment]
It compiles perfectly, I’m using it right now!

Il giorno 13/mar/2019, alle ore 12:05, Keith Mifsud <notifications@github.com> ha scritto:

**Comment by roTokyo** [comment]
Hi,
I’m still trying to use target-blank plugin ...
anyway to make it short, now with your plugin installed if I run the command:
1) bundle exec jekyll serve
	site compiles and looks working as it should (external links open in different browser tab)
but if I run the command:
2) JEKYLL_ENV=production bundle exec jekyll build --config _config.yml --trace —verbose
	site do not compile I’ll attach error.txt file

Attached: error.txt, config.yml, gemfile, gemfile.lock and 1 post file.
My macbook is an old one still running osx 10.9.5


I’ll hope this will help you.

Ro


Il giorno 13/mar/2019, alle ore 15:19, Roberto calesini <roberto.calesini@gmail.com> ha scritto:

> It compiles perfectly, I’m using it right now!
> 
> Il giorno 13/mar/2019, alle ore 12:05, Keith Mifsud <notifications@github.com> ha scritto:
> 
>> Hi.. no worries 😄
>> 
>> Does the site compile without this plugin? URI is used by Jekyll itself too. It's a Ruby library. This plugin also uses it. Please let me know if the site builds fine with this plugin disabled. If it is, then I can try a few things.
>> 
>> Thanks
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 


$ JEKYLL_ENV=production bundle exec jekyll build --config _config.yml --trace --verbose
  Logging at level: debug
Configuration file: _config.yml
         Requiring: /Users/rc/Desktop/abc/source/_plugins/if_file_exists.rb
         Requiring: /Users/rc/Desktop/abc/source/_plugins/intl_reading_time.rb
         Requiring: /Users/rc/Desktop/abc/source/_plugins/italian_dates.rb
         Requiring: /Users/rc/Desktop/abc/source/_plugins/jekyll_inline_highlite.rb
         Requiring: /Users/rc/Desktop/abc/source/_plugins/nav_cat.rb
         Requiring: jekyll-sitemap
         Requiring: jekyll-paginate
         Requiring: jekyll-maps
         Requiring: jekyll-autoprefixer
         Requiring: jekyll-minifier
         Requiring: jekyll-target-blank
            Source: source
       Destination: dest
 Incremental build: disabled. Enable with --incremental
      Generating... 
           Reading: _posts/2012-01-01-romanizzazione.md
           Reading: _postTags/eventi.md
           Reading: _postTags/hiroshima.md
           Reading: _postTags/informazioni utili.md
           Reading: _postTags/itinerari.md
           Reading: _postTags/kamakura.md
           Reading: _postTags/kyoto.md
           Reading: _postTags/mangiare e bere.md
           Reading: _postTags/mostre.md
           Reading: _postTags/musica.md
           Reading: _postTags/nagasaki.md
           Reading: _postTags/racconto.md
           Reading: _postTags/templi.md
           Reading: _postTags/tokyo.md
           Reading: _postTags/tradizioni.md
        Generating: Jekyll::WithinCategoryPostNavigation finished in 1.4e-05 seconds.
        Generating: Jekyll::JekyllSitemap finished in 0.000407 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 0.000824 seconds.
         Rendering: _posts/2012-01-01-romanizzazione.md
  Pre-Render Hooks: _posts/2012-01-01-romanizzazione.md
  Rendering Liquid: _posts/2012-01-01-romanizzazione.md
  Rendering Markup: _posts/2012-01-01-romanizzazione.md
  Rendering Layout: _posts/2012-01-01-romanizzazione.md
     Layout source: site
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
URI::InvalidURIError: bad URI(is not URI?): 
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:18:in `rescue in split'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:15:in `split'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:197:in `external?'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:92:in `processable_link?'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
  /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
  /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
  /usr/local/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:65:in `process_html'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:35:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-target-blank-1.1.1/lib/jekyll-target-blank.rb:336:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:103:in `block in trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:102:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/hooks.rb:102:in `trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/document.rb:352:in `trigger_hooks'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:480:in `render_regenerated'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:463:in `block in render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `each_value'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:462:in `render_docs'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:191:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'

**Comment by roTokyo** [comment]
Sorry to disturb you again but I found where I made the mistake.
In the config.yml the url: setting was empty!
My fault of course.

thank you very much for you plugin. I really enjoy it!

Ro


Il giorno 14/mar/2019, alle ore 15:38, Roberto calesini <roberto.calesini@gmail.com> ha scritto:

**Comment by keithmifsud** [comment]
Hi @roTokyo .. very sorry for my late correspondence. Been a busy year :) Is the issue fixed on your side? If not, I can assist you this week. Thanks :)

**Comment by visoft** [comment]
Any progress on this issue? I see a PR but the build is failing.

**Comment by roTokyo** [comment]
Thanks to your help I solved the issue.

I use your work here <https://github.com/roTokyo>!

Many thanks and … hope everything is going well!

Roberto Calesini
roberto.calesini@gmail.com

> 
> Ai sensi e per gli effetti della Legge sulla tutela della riservatezza personale (DLgs. 196/03 e collegate), questa mail è destinata unicamente alle persone sopra indicate e le informazioni in essa contenute sono da considerarsi strettamente riservate.
> Qualora non fossi il destinatario, ti preghiamo di informarci immediatamente via e-mail e di eliminare il messaggio senza trattenerne copia. Ogni utilizzo non autorizzato del contenuto di questo messaggio costituisce violazione dell'obbligo di non prendere cognizione della corrispondenza altrui, salvo più grave illecito, ed espone il responsabile alle relative conseguenze civili e penali.

**Comment by hsandt** [comment]
I found the solution on this SO issue: [Ruby: URI::InvalidURIError (URI must be ascii only)](https://stackoverflow.com/a/67400648/)

I replaced the line in jekyll-target-blank.rb:196:

```rb
URI.parse(link).host != URI.parse(@site_url).host
```

with

```rb
Addressable::URI.parse(link).host != Addressable::URI.parse(@site_url).host
```

(needs Addressable gem, it happened to be installed in my project but may need to change Gemfile on yours)

I'll have to drop the plugin from my website for now. Otherwise I'll have to create a branch and send a PR but it's not my priority right now, so I'll let you handle this directly.
