### ISSUE TITLE
Cannot build Jekyll site

### ISSUE THREAD

**Issue by ianhellstrom** [keithmifsud/jekyll-target-blank#68]
My Jekyll site compiles fine without the jekyll-target-blank pluging, but when I add it to my Gemfile, I get the following:

```
LoadError: cannot load such file -- google/protobuf_c
  /Users/ian/.gems/gems/google-protobuf-3.23.0-x86_64-darwin/lib/google/protobuf.rb:51:in `require'
  /Users/ian/.gems/gems/google-protobuf-3.23.0-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
  /Users/ian/.gems/gems/google-protobuf-3.23.0-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `require'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `<top (required)>'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `require_relative'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass/embedded.rb:4:in `<top (required)>'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `require_relative'
  /Users/ian/.gems/gems/sass-embedded-1.58.3-x86_64-darwin/lib/sass-embedded.rb:4:in `<top (required)>'
  /Users/ian/.gems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `require'
  /Users/ian/.gems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
  /Users/ian/.gems/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `require'
  /Users/ian/.gems/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /Users/ian/.gems/gems/jekyll-4.3.2/lib/jekyll.rb:195:in `require'
  /Users/ian/.gems/gems/jekyll-4.3.2/lib/jekyll.rb:195:in `<top (required)>'
  /Users/ian/.gems/gems/jekyll-4.3.2/exe/jekyll:8:in `require'
  /Users/ian/.gems/gems/jekyll-4.3.2/exe/jekyll:8:in `<top (required)>'
  /Users/ian/.gems/bin/jekyll:23:in `load'
  /Users/ian/.gems/bin/jekyll:23:in `<top (required)>'
```

My Gemfile looks like this:

```
source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-paginate-v2", "~> 3.0.0"
  gem "jekyll-target-blank", "~> 2.0.2"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

```

Moreover,

```
bundle info google-protobuf_c
The dependency http_parser.rb (~> 0.6.0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Could not find gem 'google-protobuf_c'.
```

**Comment by keithmifsud** [comment]
I think you need to install this gem `gem install --platform ruby google-protobuf` as your version is only for Java. Please let me know if this solved the issue.

**Comment by ianhellstrom** [comment]
Unfortunately, that did not solve the problem. Same issue when running `bundle exec jekyll serve` or even `... clean`.

**Comment by keithmifsud** [comment]
The error seems detailed enough:

```bash
bundle info google-protobuf_c
The dependency http_parser.rb (~> 0.6.0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Could not find gem 'google-protobuf_c'.
```

Have you tried to follow the suggestion above?

```bash
bundle lock --add-platform java
````

**Comment by ianhellstrom** [comment]
Yes, and that did nothing.

**Comment by keithmifsud** [comment]
Thanks for testing. Unfortunately, I cannot help further. You'll need to enquire with the http_parser developers.

**Comment by ianhellstrom** [comment]
I doubt that's the problem, because this is my Gemfile _before_ adding jekyll-target-blank:

```
source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15.1"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-paginate-v2", "~> 3.0.0"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

And that works fine. It's when I add jekyll-target-blank that the errors start.

**Comment by keithmifsud** [comment]
Please try removing `gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]` and adding ` gem "jekyll-target-blank", "~> 2.0.2"`
